name: Renovate SelfHosted
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - 'rel/**'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref_name }}

      - name: Get current branch
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_BASE_BRANCHES: ${{ steps.vars.outputs.BRANCH_NAME }}